
spring:
  application:
    name: Development Environment
    eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9090
